### ISSUE TITLE
No se crean los directorios del usuario correctamente

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-control#12]
Al dar de alta un usuario se deberían crear los dos siguientes directorios de usuario:
/home/samba/profiles/usuario
/home/samba/profiles/usuario.V2

El directorio "usuario.V2" no se crea pero además se esta creando el directorio repetidos en "/home":
/home/usuario

Si elimino el usuario se borra el "/home/samba/profiles/usuario" pero no el "/home/usuario"

Si pruebo a crear un usuario desde el panel de zentyal pasa lo mismo. Antes de instalar max-control o quizás fue antes de actualizar la distribución, un usuario que creé lo hizo bien.
Imagino que algo ha cambiado en el smb.conf. Voy a restaurar el servidor a ver si comparando antes de instalar el "max-control" se observa algo.

**Comment by rroobbeerr** [comment]
El problema de que no se crea el directorio "/home/samba/profiles/usuario.V2" se soluciona eliminando la sección "[profiles]" del fichero "/etc/samba/shares.conf", esta sección tiene dos parámetros, cualquiera de los dos produce el problema, así que concretamente hay que eliminar las tres líneas:
```
[profiles]
    store dos attributes = yes
    ea support = yes
```
Teniendo en cuenta que el dominio con el que estoy probando se llama "iit.lan", se observa que el shares.conf tiene dos rutas que hacen referencia a él:
```
path = /home/IIT/%S
template homedir = /home/IIT/%S
```
El problema es que no existe el directorio "/home/IIT" y por eso parece ser que los usuarios se crean en home. Si creo el directorio "/home/IIT" los usuarios nuevos se crean ahí, aunque siguo sin entender para qué crea esos usuarios cuando los perfiles de los usuarios de windows los guarda en "/home/samba/profiles/usuario.V2".

Entonces el funcionamiento final queda de la siguiente manera. Cuando se da de alta un usuario en el max-control se crean estos dos directorios:
     /home/IIT/usuario
     /home/samba/profiles/usuario
Cuando se inicia por primera vez la sesión en Windows(probado con Windows 7) es cuando se crea el directorio donde realmente guarda su perfil:
     /home/samba/profiles/usuario.V2

**Comment by mariodebian** [comment]
En Windows menores que 10 se usa /home/samba/profiles/usuario.V2, en Windows10 (creator update) se usa usuario.V6

En MAX se usa /home/usuario como perfil de roaming...
