### ISSUE TITLE
Los usuarios que se crean desde Zentyal se ven distintos en max-control

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-control#15]
Los usuarios que se crean desde el panel de administración de zentyal se muestran incorrectamente en el panel de max-control. En el siguiente pantallazo se observa como en la columna "Identificador" se muestra lo mismo que en la columna "Nombre y Apellidos":
![screenshot from 2017-07-24 10-35-42](https://user-images.githubusercontent.com/6009465/28514925-117a9d62-705c-11e7-9c5b-9956105aa1b7.png)

Al poner el ratón en la estrella verde que tienen muestra "Perfil sin roaming". Los centros sólo van a utilizar el panel de max-control para crear los usuarios, pero estaría bien si se puede compatibilizar el funcionamiento entre los dos paneles.

**Comment by mariodebian** [comment]
Modificar Zentyal para que cree perfiles con romaing es demasiado complejo, sí podemos hacer que se pinte el nombre de usuario en la primera columna en lugar de Nombre+Apellidos para que concuerde con el resto....
