### ISSUE TITLE
Pantalla en blanco al editar un equipo

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-control#16]
En el listado de equipos si editas un equipo para ponerle la MAC e IP, al darle a "Guardar" se queda la pantalla en blanco sin embargo los cambios quedan guardados. Lo normal sería que volviese al listado de equipos.

**Comment by mariodebian** [comment]
En mi instalación de pruebas no guarda, da dos errores acerca de permisos y luego llama a una función que no existe (se puede ver con el DEBUG activado)
