### ISSUE TITLE
Se pierde la configuración de /etc/samba/shares.conf

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-control#21]
Cada vez que se reinicia el servidor o se hace un cambio de configuración en el panel de zentyal se restaura el fichero "/etc/samba/shares.conf" perdiendose las personalizaciones de max-control.

**Comment by mariodebian** [comment]
El archivo /etc/samba/shares.conf lo genera Zentyal a partir de una plantilla (igual que /etc/samba/smb.conf) => https://github.com/zentyal/zentyal/tree/master/main/samba/stubs

max-control incluye un script para actualizarlo: pymaxgensamba que cuando se ejecuta lo edita para que max-control funcione mejor.... pero este script no se llama sólo si no tienes instalado zentyal-maxcontrol

Instala el paquete zentyal-maxcontrol (está arreglado ayer desde la 5.0~max5)

Este paquete incluye varios hooks que hacen que se ejecute pymaxgensamba después de modificarse los archivos y antes de reiniciar samba. ( https://github.com/max-linux/max-control/tree/master/zentyal-maxcontrol/usr/share/zentyal-maxcontrol/hooks )
