### ISSUE TITLE
Los menús de persiana han dejado de funcionar

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-control#22]
A raíz de la actualización "5.0~max6" los menús que se despliegan en forma de persiana como cuando le das a la flecha azul para editar las propiedades de un usuario, un aula o el menú que aparece en el icono superior derecho que indica el usuario con el que se ha iniciado sesión, ha dejado de funcionar, no se despliega, simplemente le das y no pasa nada.
![no_se_despliega_el_menu](https://user-images.githubusercontent.com/6009465/28662743-82deffaa-72bb-11e7-879b-bd6fa8eef285.png)

He probado con los navegadores firefox y con chrome.

**Comment by rroobbeerr** [comment]
Super curioso, si activo el debug en "/etc/max-control/conf.inc.php" entonces sí funcionan los menús, lo desactivo y dejan de funcionar.

**Comment by mariodebian** [comment]
El DEBUG=True carga distintos css y js (sin minimizar) puede que falte re-minimizar algunos archivos...
