### ISSUE TITLE
No funciona el menu por pxe

### ISSUE THREAD

**Issue by rroobbeerr** [max-linux/max-control#26]
Cuando configuro el arranque por PXE en un equipo, este al iniciar muestra el mensaje del DHCP:

DHCP....

pero finalmente pasa el tiempo y muestra un error indicando que no se ha podido recuperar un menu PXE. Ni le asigna IP ni nada.

**Comment by rroobbeerr** [comment]
Ya he conseguido que funcione. Faltaba por instalar el paquete atftpd y configurar el servicio DHCP(isc-dhcp.server). El problema es que seguro que los cambios realizados en el fichero del DHCP se pierden al reiniciar la máquina. He seguido los siguientes pasos:

`sudo apt install atftpd`

Configurar el fichero "/etc/default/atftpd" con el siguiente contenido:

```
USE_INETD=false
OPTIONS="--tftpd-timeout 300 --retry-timeout 5 --mcast-port 1758 --mcast-addr 239.239.239.0-255 --mcast-ttl 1 --maxthread 100 --verbose=5 /var/lib/tftpboot"
```
`sudo systemctl restart atftpd`

Configurar el fichero "/etc/dhcp/dhcpd.conf". En la "subnet" correspondiente a la red local añadir:

```
#option 66
option tftp-server-name "172.20.10.1";
#option 67
option bootfile-name "pxelinux.0";
```
Reiniciar el servicio DHCP:
`sudo systemctl restart isc-dhcp-server.service`

Miraré a ver si puedo crear el script correspondiente en "/etc/zentyal/hooks" para poder conservar estos cambios.

**Comment by rroobbeerr** [comment]
He creado el siguiente script que hay que copiar en "/etc/zentyal/hooks" y darle permisos 755:
[dhcp.postsetconf.zip](https://github.com/max-linux/max-control/files/1332844/dhcp.postsetconf.zip)
Con el ya consigo personalizar la configuración de "/etc/dhcp/dhcpd.conf". El único problema es que el script lleva una variable "interfaz=eth1" para determinar la interfaz que hay que configurar. En caso de que no sea "eth1" habría que modificarla.

**Comment by mariodebian** [comment]
En la configuración avanzada DHCP se puede poner esto

![zentyal-pxe](https://user-images.githubusercontent.com/522472/30918990-724f69e8-a3a0-11e7-8ccf-f46301edd8ff.png)

Creo que no es necesario ningún script

**Comment by rroobbeerr** [comment]
Ya te digo que con eso vale. Lo bueno es que había visto esa configuración pero pasé completamente de ella, pensé que sería para su servidor TFTP pero que carajo si esto es para el DHCP y por defecto veo que él no instala ningún servicio TFTP, en fin,  gracias Mario.

Bueno ahí queda el script para ejemplo por si toca hacer alguna otra configuración extra que espero que no ;-)

**Comment by mariodebian** [comment]
en el commit aaec23a he añadido como dependencia atftpd y un script para configurarlo, con esto (y sin tu script) arrancan los equipos por PXE. Todavia no he subido nueva versión del paquete...
